### ISSUE TITLE
Slow Performance?

### ISSUE THREAD

**Issue by TroySigX** [zbirenbaum/copilot-cmp#59]
Using [cmp-copilot](https://github.com/hrsh7th/cmp-copilot), I usually get the suggestion almost immediately, while for this plugin I sometimes have to wait for around 5 seconds.

**Comment by zbirenbaum** [comment]
That definitely should not be the case, my completions are nearly instant and I used cmp-copilot as a benchmark during development. Can you provide your config as well as the contents of a file where this issue is reproducible?

**Comment by TroySigX** [comment]
Here's my config:
``` lua
vim.g.copilot_no_tab_map = true
vim.g.copilot_enabled = false
vim.cmd([[set completeopt=menu,menuone,noselect]])

local has_words_before = function()
    unpack = unpack or table.unpack
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end

local cmp = require('cmp')

cmp.setup({
    mapping = cmp.mapping.preset.insert({
    ['<C-Space>'] = cmp.mapping.complete{ reason = cmp.ContextReason.Auto },
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<Tab>'] = cmp.mapping(function(fallback)
        if not cmp.select_next_item() then
            if vim.bo.buftype ~= 'prompt' and has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
        if not cmp.select_prev_item() then
            if vim.bo.buftype ~= 'prompt' and has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end
    end, { 'i', 's' }),
    }),

    sources = {
        { name = 'nvim_lsp' },
        { name = 'buffer' },
        { name = 'nvim_lsp_signature_help' },
        { name = 'luasnip' },
        { name = 'copilot' },
    },

    snippet = {
        expand = function(args)
            require('luasnip').lsp_expand(args.body)
        end,
    },
})

cmp.setup.cmdline('/', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
        { name = 'buffer' }
    }
})
```

**Comment by TroySigX** [comment]
I just open a new cpp file and ask copilot to write a function to check whether a number is prime or not (using comment). Then I go down to a new line and start typing `bool` (as a trigger) and wait for it to respond.

**Comment by clotodex** [comment]
My performance is also surprisingly slow, it can take up to 10s sometimes for a result to show up

**Comment by zbirenbaum** [comment]
I noticed some decent lag at the start while the lsp is spinning up and for larger function bodies during tests. If you just opened a new file then it will seem like there's a big delay, but there shouldn't be much once it's working.

If you aren't referring to that specific case (which is configurable through changing your lazy loading parameters) I think this might be related to cmp debouncing or throttling, which is luckily configurable. 

Jus to make sure though, I'll see if there's any real delay due to inefficiency between the response and output on copilot-cmp's end. I take performance issues very seriously so this will be fixed asap if it's something on my end.

**Comment by TroySigX** [comment]
I believe it's not because of nvim-cmp. Because when I tried copilot.vim along with [cmp-copilot](https://github.com/hrsh7th/cmp-copilot) (written by hrsh7th) as source, I got very quick response.

**Comment by zbirenbaum** [comment]
> I believe it's not because of nvim-cmp. Because when I tried copilot.vim along with [cmp-copilot](https://github.com/hrsh7th/cmp-copilot) (written by hrsh7th) as source, I got very quick response.

I am aware of this plugin and have used it myself. Are you referring to delay over the course of editing or when first opening a file?

**Comment by TroySigX** [comment]
It was when first opening a file.

**Comment by zbirenbaum** [comment]
> It was when first opening a file.

This is just due to how the lazy loading works in the default setup. I'll see if I can put an example with less startup lag in the readme

**Comment by TroySigX** [comment]
Hi, is there any update on this? I have have very slow startup time

**Comment by TroySigX** [comment]
I notice that right after opening a file, going to `insert` mode, then press `Esc` (to go back to normal mode), and then go to `insert` mode again, everything works properly.

**Comment by zbirenbaum** [comment]
> I notice that right after opening a file, going to `insert` mode, then press `Esc` (to go back to normal mode), and then go to `insert` mode again, everything works properly.

So standard practice for cmp sources is to setup on `InsertEnter`, but since copilot might not have loaded yet depending on your config, you are also trying to load copilot which is a bit slower.

I pushed an update, try configuring copilot-cmp with `require('copilot_cmp').setup({ event = 'LspAttach' })` 

Sorry for the delay. I am working 2 jobs atm and both are very time consuming so I've been a bit burnt out

**Comment by TroySigX** [comment]
Thank you so much for your dedication @zbirenbaum, it works now!
